var war = [
		"As the grim lion fawneth o'er his prey",
		"Sharp hunger by the conquest satisfied",
		"And they, like straggling slaves for pillage fighting",
		"Obdurate vassals fell exploits effecting",
		"His eye, which late this mutiny restrains",
		"Unto a greater uproar tempts his veins",
		"In bloody death and ravishment delighting",
		"Nor children's tears nor mothers' groans respecting",
		"Swell in their pride, the onset still expecting",
		"Anon his beating heart, alarum striking",
		"Gives the hot charge and bids them do their liking",
		"His hand, as proud of such a dignity",
		"Smoking with pride, marched on to make his stand",
		"Who, peeping forth this tumult to behold",
		"Are by his flaming torch dimmed and controlled",
		"Wounding itself to death, rise up and fall",
		"Beating her bulk, that his hand shakes withal",
		"This moves in him more rage and lesser pity",
		"To make the breach and enter this sweet city",
		"Not marble, nor the gilded monuments",
		"Of princes, shall outlive this powerful rhyme",
		"But you shall shine more bright in these contents",
		"Than unswept stone, besmeared with sluttish time",
		"When wasteful war shall statues overturn",
		"And broils root out the work of masonry",
		"Nor Mars his sword nor war's quick fire shall burn",
		"The living record of your memory",
		"'Gainst death and all-oblivious enmity",
		"Shall you pace forth; your praise shall still find room",
		"Even in the eyes of all posterity",
		"That wear this world out to the ending doom",
		"Now the hungry lion roars",
		"And the wolf behowls the moon",
		"Now the wasted brands do glow",
		"Whilst the screech-owl, screeching loud",
		"Puts the wretch that lies in woe",
		"In remembrance of a shroud",
		"Hath not old customs make this life more sweet",
		"More free from peril than the envious court",
		"Here feel we not the penalty of Adam",
		"Sweet are the uses of adversity",
		"Which, like the toad, ugly and venomous",
		"Wears yet a precious jewel in his head",
		"Th' expense of spirit in a waste of shame",
		"Is perjured, murderous, bloody full of blame",
		"Savage, extreme, rude, cruel, not to trust",
		"Enjoyed no sooner but despisèd straight",
		"Past reason hunted, and no sooner had",
		"Past reason hated as a swallowed bait",
		"Mad in pursuit, and in possession so",
		"Had, having, and in quest to have, extreme",
		"A bliss in proof, and proved, a very woe",
		"To shun the heaven that leads men to this hell",
		"Devouring Time blunt thou the lion's paws",
		"And make the earth devour her own sweet brood",
		"Pluck the keen teeth from the fierce tiger's jaws",
		"And burn the long-lived phoenix, in her blood",
		"Or some fierce thing replete with too much rage",
		"Whose strength's abundance weakens his own heart",
		"And in themselves their pride lies burièd",
		"For at a frown they in their glory die",
		"The painful warrior famousèd for fight",
		"After a thousand victories once foiled",
		"Is from the book of honour razèd quite",
		"When sometime lofty towers I see down-razed",
		"And brass eternal slave to mortal rage",
		"The evil that men do lives after them",
		"O judgment! thou art fled to brutish beasts",
		"The fewer men, the greater share of honour",
		"God's will! I pray thee, wish not one man more",
		"A soldier's a man; a life's but a span",
		"Why, then, let a soldier drink",
		"Th' infenal Serpent, whose guile",
		"Stirred up with envy and revenge",
		"Against the monarchy of God",
		"Raised impious war in heaven",
		"And battled proud with vain attempt",
		"Hurled headlong from th' etereal sky",
		"With hideous ruin and combustion down",
		"To bottomless perdition, there to dwell",
		"In adamantine chains and fire",
		"Who darest defy the Omnipotent to arms",
		"To mortal men, he with his horrid crew",
		"Lay vanquished, rowling in the fiery gulf",
		"But his doom reserved more wrath",
		"Both of lost joy and lasting pain",
		"The thought torments his baleful eyes",
		"That witnessed affliction and dismay",
		"With obdurate pride and steadfast haste",
		"A dungeon horrid, on all sides round",
		"As one great furnace flam'd, and yet",
		"Such flames bequeath nary a gleam",
		"Still urges, and a fiery deluge, fed",
		"With e'er-burning sulphur unconsumed",
		"For those rebellious, their prison ordained",
		"As far removed from light of Heaven",
		"As from Center thrice to Pole",
		"How unlike the place from whence they fell!",
		"With whirlwinds of tempestuous fire",
		"If thou beest he, but o how fallen!",
		"Whom mutual league united counsels",
		"Equal hope and hazard in glorious enterprise",
		"Joined with me once, now misery joined",
		"Who knew the force of those dire arms?",
		"Nor what the potent victor in his rage",
		"And to the fierce contention brought",
		"Innumerable force of spirits armed",
		"His utmost with adverse power opposed",
		"In dubious battle on Heaven's plain",
		"All is not lost; the unconquerable Will",
		"The studied revenge, the immortal hate",
		"The courage ne'er to yield or submit",
		"Shall ne'er his wrath extort from me",
		"To sue fo grace with supplicant knee",
		"Who from the terror of this arm",
		"That were an ignominy and shame",
		"And this Empyreal substance cannot fail",
		"In arms not worse, in foresight advanced",
		"We may with greater hope resolve",
		"To wage by force or guile eternal war",
		"Irreconcileable to our grand foe",
		"Sole reigning holds the tyranny of heaven",
		"That led the imbattled seraphim to war",
		"In dreadful deeds e'er fearless",
		"Endangered heaven's perpetual king",
		"Put to proof his high supremacy",
		"And foul defeath hath lost us Heaven",
		"In horrible destruction laid thus low",
		"For the mind and spirit remains",
		"As being contrary to his high will",
		"Our sole delight to e'er do ill",
		"The angry victor hath recalled",
		"His ministers of vengeance and pursuit",
		"The sulphurous hail shot after us",
		"O'er blown hath laid the fiery surge",
		"That from the precipice reciev'd us falling",
		"Wingd with red lightning and impetuous rage",
		"To bellow through the boundless deep",
		"Yield such fury from our foe",
		"Seest thou yon dreary plain",
		"Forlorn and wild, devoid of light",
		"These livid flames cast pale and dreadful",
		"From off the tossing o' these fiery waves",
		"And reassembling our afflicted Powers",
		"Consult how we may henceforth offend",
		"Our own loss how we repair",
		"How overcome this dire calamity",
		"What reinforcement we may gain from Hope",
		"If not what resolution from despair",
		"Chained upon the burning lake",
		"Left at large to his own dark designs",
		"That he might heap on himself damnation",
		"Confusion, wrath, and vengeance pour'd",
		"Upright he rears from off the pool",
		"His mighty stature, on each hand flames",
		"Leave in their mist a horrid vale",
		"Aloft, incumbent on dusky air",
		"Torn from Pelorus, or the shattered side",
		"And fueled entrails thus conceiving fire",
		"Sublimed with mineral fury, aid the winds",
		"To escape the Stygian flood as gods",
		"Better to reign in Hell than serve in Heaven",
		"The associates and copartners of our loss",
		"Once more to try with rallied arms",
		"What may be yet regained in Heaven",
		"Which but the Omnipotent none could foil",
		"O leader of those armies bright",
		"Their pledge of hope in fears and dangers",
		"Heard so oft in worst extremes",
		"On the perilous edge of battle it raged",
		"They soon resume new courage and life",
		"Groveling and prostrate on yon lake of fire",	
		"Fallen such a pernicious height",
		"His ponderous shield, ethereal temper",
		"Hung on his shoulders like the Moon",
		"His spear, to equal the tallest pine",
		"The admiral's mast were but a wand",
		"Uneasy steps o'er burning marl",
		"Not like those steps on heaven's azure",
		"The torrid clime smote sore besides",
		"Vaulted with fire, he so endured",
		"On the beach he called his legions",
		"Beheld from the shore their floating carcasses",
		"And broken chariot wheels bestrown",
		"Abject and lost lay in the deluge",
		"In amazement of this hideous change",
		"Princes, potentates, warriors!",
		"With scattered ensigns, till anon",
		"His swift pursuers from heaven's gates",
		"Discern the advantage, and tread us down",
		"Awake, arise, or be forever fallen!",
		"Yet to their general's voice soon obeyed",
		"Warping on the eastern wind",
		"That oe'r the realm of the impious Pharaoh",
		"Hung like night and darkened the Nile",
		"So innumerable were these daemons seen",
		"Hovering under the cope of hell",
		"'Twixt upper, nether, and surrounding fires",
		"The uplifted spear of their great Sultan",
		"Down they light on the firm brimstone",
		"When her barbarous sons came like a deluge",
		"Forthwith from every squadron and band",
		"Godlike shapes and forms excelling human",
		"Razed by their rebellion from the Book of Life",
		"To transform oft to the image of a brute",
		"Adorned with religions of pomp and gold",
		"And devils to adore for deities",
		"And idols through the heathen world",
		"His rites and solemn feasts profaned",
		"First horrid King besmeared with blood",
		"Through the noise of drums and timbrels loud",
		"To do him wanton rites of woe",
		"Ten thousand banners rose to the air",
		"With orient colours waving high",
		"With them rose a forest of spears",
		"And thronging helms and plates appeared",
		"And serried shields in thick array",
		"Of depth immeasurable, anon they move",
		"In perfect phalanx to the Dorian mood",
		"Valour breathed, firm and unmov'd",
		"Breathing united force with fixed thought",
		"A horrid front of dreadful length",
		"Of warriors old with spear and shield",
		"He through the files darts his eye",
		"Their visages and stature as of gods",
		"And now his heart distends with prie",
		"He, hardening in his strength, glories",
		"He above the rest stood like a Tower",
		"His form had not yet lost her brightness",
		"Nor appeared less than archangel ruined",
		"And the excess of her glory obscured",
		"As looks the sunrise on misty air",
		"In dim eclipse disastrous twilight sheds"
	];
var love = [
		"The barge she sat in, like a burnish'd throne",
		"Purple the sails, and so perfumed",
		"The winds were lovesick with them",
		"For her own person, it beggar'd all description",
		"Her pavilion, cloth-of-gold of tissue",
		"Like smiling Cupids, with divers-colour'd fans",
		"To glow the delicate cheeks which they did cool",
		"So many mermaids, tended her i' th' eyes",
		"Swell with the touches of those flower-soft hands",
		"Age cannot wither her, nor custom stale",
		"Roses, their sharp spines being gone",
		"Maiden pinks, of odour faint",
		"Daisies smell-less, yet most quaint",
		"And sweet thyme e'er true",
		"All dear Nature's children sweet",
		"Lie 'fore bride and bridegroom's feet",
		"Not an angel of the air",
		"Bird melodious or bird fair",
		"Her lily hand her rosy cheek lies under",
		"Cozening the pillow of a lawful kiss",
		"Swelling on either side to want his bliss",
		"Between whose hills her head entombed is",
		"Where like a virtuous monument she lies",
		"Without the bed her other fair hand was",
		"On the green coverlet, whose perfect white",
		"Showed like an April daisy on the grass",
		"With pearly sweat resembling dew of night",
		"Her eyes, like marigolds, had sheathed their light",
		"And canopied in darkness sweetly lay",
		"Till they might open to adorn the day",
		"Her hair like golden threads played with her breath",
		"Each in her sleep themselves so beautify",
		"Her breasts like ivory globes circled with blue",
		"A pair of maiden worlds unconquered",
		"What he beheld, on that he firmly doted",
		"With more than admiration he admired",
		"Her azure veins, her alabaster skin",
		"Her coral lips, her snow-white dimpled chin",
		"On her bare breast, the heart of all her land",
		"Tell me where is Fancy bred",
		"Or in the heart or in the head",
		"It is engender'd in the eyes",
		"O mistress mine, where are you roaming?",
		"O stay and hear! your true-love's coming",
		"That can sing both high and low",
		"Trip no further, pretty sweeting",
		"Journey's end in lovers' meeting",
		"What is love? 'tis not hereafter",
		"Present mirth hath present laughter",
		"Then come kiss me, Sweet and twenty",
		"Youth's a stuff will not endure",
		"O never say that I was false of heart",
		"Though absence seem'd my flame to qualify",
		"Like him that travels, I return again",
		"For nothing this wide universe I call",
		"Save thou, my rose: in it thou art my all",
		"Holy, fair, and wise is she",
		"The heaven such grace did lend her",
		"That she might admired be",
		"Is she kind as she is fair?",
		"For beauty lives with kindness",
		"Love doth to her eyes repair",
		"To help him of his blindness",
		"And, being help'd, inhabits there",
		"She excels each mortal thing",
		"To her let us garlands bring",
		"O, how much more doth beauty beauteous seem",
		"By that sweet ornament which truth doth give",
		"The rose looks fair, but fairer we it deem",
		"The canker-blooms have full as deep a dye",
		"As the perfumed tincture of the roses",
		"And so of you, beauteous and lovely youth",
		"When that shall fade, my verse distills your truth",
		"My love is strengthened, though more weak in seeming",
		"I love not less, though less the show appear",
		"Our love was new, and then but in the spring",
		"When I was wont to greet it with my lays",
		"Let not my love be called idolatry",
		"To one, of one, still such, and ever so",
		"Kind is my love today, tomorrow kind",
		"Still constant in a wondrous excellence",
		"Even such a beauty as you master now",
		"They had not skill enough your worth to sing",
		"Then, in the blazon of sweet beauty's best",
		"Have eyes to wonder, but lack tongues to praise",
		"Counting no old thing old- thou mine, I thine-",
		"Even as when first I hallowed thy fair name",
		"So that eternal love in love's fresh case",
		"Weighs not the dust and injury of age",
		"Thou art the fairest and most precious jewel",
		"For well thou know'st to my dear doting heart",
		"Cupid laid by his brand and fell asleep",
		"And his love-kindling fire did quickly steep",
		"Which borrowed from this holy fire of Love",
		"The little love god lying once asleep",
		"The fairest votary took up that fire",
		"Which many legions of true hearts had warmed",
		"And so the general of hot desire",
		"Love's fire heats water, water cools not love",
		"On Helen's cheek all art of beauty set",
		"And you in Grecian tires are painted new",
		"Who in the happy realms of light",
		"Clothèd in transcendent brightness",
		"Did outshine myriads through bright",
		"So uncompounded is their essence pure",
		"And works of love or enmity fulfill",
		"Whose wanton passions in the sacred porch"
	];
var springsummer = [
		"Over hill and over dale",
		"Through the bush and through the briar",
		"Over park and over pale",
		"Through the flood and through the fire",
		"I do wander everywhere",
		"Swifter than the moon's sphere",
		"And I serve the Fairy Queen",
		"To dew her orbs upon the green",
		"The cowslips tall her pensioners be",
		"In their gold coats spots you see",
		"Those be rubies, fairy favours",
		"In those freckles live their savours",
		"I must go seek some dewdrops here",
		"And hang a pearl in every cowslip's ear",
		"Hark! hark! the lark at heaven's gate sings",
		"And Phoebus 'gins arise",
		"His steeds to water at those springs",
		"On chaliced flowers that lies",
		"And winking Mary-buds begin",
		"To ope their golden eyes",
		"With everything that pretty bin",
		"My lady sweet, arise!",
		"Primrose, firstborn child of Ver",
		"Merry springtime's harbinger",
		"Oxlips in their cradles growing",
		"Marigolds on death-beds blowing",
		"It was a lover and his lass",
		"That o'er the green corn-field did pass",
		"In the spring time, the only pretty ring time",
		"Sweet lovers love the spring",
		"Between the acres of the rye",
		"These pretty country folks would lie",
		"This carol they began that hour",
		"How that life was but a flower",
		"And, therefore, take the present time",
		"For love is crown`d with the prime",
		"Orpheus with his lute made trees",
		"And the mountain tops that freeze",
		"Bow themselves, when he did sing",
		"To his music plants and flowers",
		"Ever sprung; as sun and showers",
		"There had made a lasting spring",
		"Everything that heard him play",
		"Even the billows of the sea",
		"Hung their heads, and then lay by",
		"In sweet music is such art",
		"When daisies pied and violets blue",
		"And lady-smocks all silver-white",
		"And cuckoo-buds of yellow hue",
		"Do paint the meadows with delight",
		"Love, whose month is ever May",
		"Spied a blossom passing fair",
		"Playing in the wanton air",
		"Through the velvet leaves the wind",
		"All unseen 'gan passage find",
		"Air, quoth he, thy cheeks may blow",
		"Air, would I might triumph so",
		"Where the bee sucks, there suck I",
		"In a cowslip's bell I lie",
		"There I couch when owls do cry",
		"On the bat's back I do fly",
		"Merrily, merrily, shall I live now",
		"Under the blossom that hangs on the bough",
		"Come unto these yellow sands",
		"And kiss'd the wild waves whist",
		"The strain of strutting chanticleer",
		"Full fathom five thy father lies",
		"Of his bones are coral made",
		"Those are pearls that were his eyes",
		"Sea-nymphs hourly ring his knell",
		"Shall I compare thee to a summer's day?",
		"Thou art more lovely and more temperate",
		"Rough winds do shake the darling buds of May",
		"And summer's lease hath all too short a date",
		"Sometime too hot the eye of heaven shines",
		"And often is his gold complexion dimmed",
		"And every fair from fair sometime declines",
		"By chance, or nature's changing course, untrimmed",
		"But thy eternal summer shall not fade",
		"Nor lose possession of that fair thou ow'st",
		"Hang on such thorns and play as wantonly",
		"When summer's breath their masked buds discloses",
		"Of their sweet deaths are sweetest odours made",
		"As Philomel in summer's front doth sing",
		"And stops her pipe in growth of riper days",
		"Than when her mournful hymns did hush the night",
		"But that wild music burthens every bough",
		"And sweets grown common lose their dear delight",
		"Full many a glorious morning have I seen",
		"Flatter the mountaintops with sovereign eye",
		"Kissing with golden face the meadows green",
		"Gilding pale streams with heavenly alchemy",
		"Anon permit the basest clouds to ride",
		"With ugly rack on his celestial face",
		"With all-triumphant splendour on my brow",
		"Suns of the world may stain when heaven's sun staineth",
		"'Tis not enough that through the cloud thou break",
		"To dry the rain on my storm-beaten face",
		"Bringeth forth fruits of thy kind",
		"Waters under heaven gathered",
		"A greater light to rule the day",
		"A lesser light to rule the night",
		"Set upon the firmament",
		"There went a mist upon the earth",
		"With bdellium and the onyx stone",
		"With head uplift above the waves",
		"And eyes of gold that sparkling blazed",
		"Haply slumbering on the Norway foam",
		"The pilot of some night-founder'd skiff",
		"With fixed anchor in scaly rind",
		"Moors by his side under the lee",
		"Night invests the sea, and morn delays"
	];
var fallwinter = [
		"Blow, blow, thou winter wind",
		"Thou art not so unkind as man's ingratitude",
		"Heigh-ho! sing, heigh-ho! unto the green holly",
		"Most freindship if feigning, most loving mere folly",
		"Freeze, freeze thou bitter sky",
		"That does not bite so nigh as benefits forgot",
		"Thy sting is not so sharp as a friend remembered not",
		"Imagine her as one in dead of night",
		"From forth dull sleep by dreadful fancy waking",
		"That thinks she hath beheld some ghastly sprite",
		"Whose grim aspect sets every joint a-shaking",
		"Wrapped and confounded in a thousand fears",
		"Like to a new-killed bird she trembling lies",
		"The seasons difference; as the icy fang",
		"And churlish chiding of the winters wind",
		"Whilst the heavy ploughman snores",
		"All with weary task fordone",
		"Which when it bites and blows upon my body",
		"Even till I shrink with cold, I smile and say",
		"Some say that ever gainst that season comes",
		"Wherein our Saviour's birth is celebrated",
		"This bird of dawning singeth all night long",
		"And then, they say, no spirit dare stir abroad",
		"The nights are wholesome, then no planets strike",
		"No fairy takes, nor witch hath power to charm",
		"So hallow'd and so gracious is the time",
		"To me, fair friend, you never can be old",
		"For as you were when first your eye I ey'd",
		"Such seems your beauty still. Three winters cold",
		"Have from the forests shook three summers' pride",
		"Steal from his figure, and no pace perceiv'd",
		"Hath motion, and mine eye may be deceiv'd",
		"For fear of which, hear this thou age unbred",
		"Ere you were born was beauty's summer dead",
		"When I do count the clock that tells the time",
		"And see the brave day sunk in hideous night",
		"When I behold the violet past prime",
		"And sable curls all silvered o'er with white",
		"When lofty trees I see barren of leaves",
		"Which erst from heat did canopy the herd",
		"And summer's green all girded up in sheaves",
		"Borne on the bier with white and bristly beard",
		"Then of thy beauty do I question make",
		"That thou among the wastes of time must go",
		"Since sweets and beauties do themselves forsake",
		"And die as fast as they see others grow",
		"When shepherds pipe on oaten straws",
		"And merry larks are ploughmen's clocks",
		"When turtles tread, and rooks, and daws",
		"And maidens bleach their summer smocks",
		"That time of year thou mayst in me behold",
		"When yellow leaves, or none, or few, do hang",
		"Upon those boughs which shake against the cold",
		"Bare ruined choirs, where late the sweet birds sang",
		"In me thou see'st the twilight of such day",
		"As after sunset fadeth in the west",
		"Which by and by black night doth take away",
		"Death's second self, that seals all up in rest",
		"In me thou see'st the glowing of such fire",
		"That on the ashes of his youth doth lie",
		"As the deathbed whereon it must expire",
		"Consumed with that which it was nourished by",
		"When icicles hang by the wall",
		"And Cain bears logs into the hall",
		"And milk comes frozen home in pail",
		"When Blood is nipped and ways be foul",
		"Then nightly sings the staring owl",
		"While greasy Joan doth keel the pot",
		"When all aloud the wind doth blow",
		"And coughing drowns the parson's saw",
		"And birds sit brooding in the snow",
		"And Maria's nose looks red and raw",
		"When roasted crabs hiss in the bowl",
		"You spotted snakes with double tongue",
		"Thorny hedgehogs, be not seen",
		"Newts and blind-worms, do no wrong",
		"Come not near our fairy queen",
		"Philomel, with melody",
		"Sing in our sweet lullaby",
		"Never harm, nor spell nor charm",
		"Come our lovely lady nigh",
		"Weaving spiders, come not here",
		"Hence, you long-legg'd spinners, hence!",
		"Beetles black, approach not near",
		"Worm nor snail, do no offence",
		"Like as the waves make towards the pebbled shore",
		"So do our minutes hasten to their end",
		"Each changing place with that which goes before",
		"In sequent toil all forwards do contend",
		"Crookèd eclipses 'gainst his glory fight",
		"And Time that gave doth now his gift confound",
		"Feeds on the rarities of nature's truth",
		"And nothing stands but for his scythe to mow",
		"O, how shall summer's honey breath hold out",
		"Against the wrackful siege of batt'ring days",
		"The earth was without form, and void",
		"Dark upon the face of deep",
		"Of that Forbidden Tree, whose mortal tast",
		"Bought Death into the world, and woe",
		"As autumnal leaves that strow the brooks",
		"When the fierce winds orion armed",
		"Whose waves oe'rthrew his Memphian chivalry"
	];
var fate = [
		"All the world's a stage",
		"And all the men and women merely players",
		"They have their exits and their entrances",
		"And one man in his time plays many parts",
		"His acts being seven ages",
		"Our remedies oft in ourselves do lie",
		"Which we ascribe to heaven",
		"The fated sky gives us free scope",
		"What power is it which mounts my love so high",
		"The mightiest space in fortune nature brings",
		"That weigh their pains in sense and do suppose",
		"What hath been cannot be",
		"Not from the stars do I my judgement pluck",
		"And yet methinks I have astronomy",
		"But not to tell of good, or evil luck",
		"Of plagues, of dearths, or seasons' quality",
		"Nor can I fortune to brief minutes tell",
		"Pointing to each his thunder, rain and wind",
		"Or say with princes if it shall go well",
		"By oft predict that I in heaven find",
		"But from thine eyes my knowledge I derive",
		"And constant stars in them I read such art",
		"As truth and beauty shall together thrive",
		"If from thy self, to store thou wouldst convert",
		"Or else of thee this I prognosticate",
		"Thy end is truth's and beauty's doom and date",
		"What's to come is still unsure",
		"In delay there lies no plenty",
		"Nor shall death brag thou wand'rest in his shade",
		"When in eternal lines to Time thou grow'st",
		"So long as men can breathe, or eyes can see",
		"So long lives this, and this gives life to thee",
		"If time have any wrinkle graven there",
		"If any, be a satire to decay",
		"And make time's spoils despisèd everywhere",
		"Give my love fame faster than Time wastes life",
		"So thou prevent'st his scythe and crooked knife",
		"When in the chronicle of wasted time",
		"I see descriptions of the fairest wights",
		"And beauty making beautiful old rhyme",
		"In praise of ladies dead, and lovely knights",
		"I see their antique pen would have expressed",
		"So all their praises are but prophecies",
		"Of this our time, all you prefiguring",
		"And, for they looked but with divining eyes",
		"Not mine own fears, nor the prophetic soul",
		"Of the wide world dreaming on things to come",
		"Can yet the lease of my true love control",
		"Suppos'd as forfeit to a confined doom",
		"The mortal moon hath her eclipse endur'd",
		"And the sad augurs mock their own presage",
		"Incertainties now crown themselves assur'd",
		"And peace proclaims olives of endless age",
		"Now with the drops of this most balmy time",
		"Since, spite of him, I'll live in this poor rhyme",
		"And thou in this shalt find thy monument",
		"When tyrants' crests and tombs of brass are spent",
		"O, for my sake do you with Fortune chide",
		"The guilty goddess of my harmful deeds",
		"That did not better for my life provide",
		"Than public means which public manners breeds",
		"No, Time, thou shalt not boast that I do change",
		"Thy pyramids built up with newer might",
		"To me are nothing novel, nothing strange",
		"They are but dressings of a former sight",
		"Thy registers and thee I both defy",
		"Not wond'ring at the present, nor the past",
		"For thy records, and what we see doth lie",
		"Made more or less by thy continual haste",
		"Who hast by waning grown, and therein show'st",
		"As thou goest onwards, still will pluck thee back",
		"Yet fear her, O thou minion of her pleasure!",
		"She may detain, but not still keep her treasure",
		"Her audit, though delayed, answered must be",
		"And her quietus is to render thee",
		"Or laid great bases for eternity",
		"Which proves more short than waste or ruining",
		"When I consider every thing that grows",
		"Holds in perfection but a little moment",
		"That this huge stage presenteth nought but shows",
		"Whereon the stars in secret influence comment",
		"When I perceive that men as plants increase",
		"Cheerèd and checked even by the self-same sky",
		"Then the conceit of this inconstant stay",
		"To change your day of youth to sullied night",
		"But wherefore do not you a mightier way",
		"Make war upon this bloody tyrant, Time",
		"And fortify your self in your decay",
		"With means more blessèd than my barren rhyme",
		"So should the lines of life that life repair",
		"Which this, Time's pencil, or my pupil pen",
		"Neither in inward worth nor outward fair",
		"To give away your self keeps your self still",
		"And you must live drawn by your own sweet skill",
		"Who will believe my verse in time to come",
		"Though yet heaven knows it is but as a tomb",
		"And in fresh numbers number all your graces",
		"So should my papers, yellowed with their age",
		"Be scorned like old men of less truth than tongue",
		"And stretchèd metre of an antique song",
		"Let those who are in favour with their stars",
		"Whilst I, whom fortune of such triumph bars",
		"If there be nothing new, but that which is",
		"Hath been before, how are our brains beguiled",
		"O, that record could with a backward look",
		"Even of five hundred courses of the sun",
		"That I might see what the old world could say",
		"Whose action is no stronger than a flower",
		"Restore us, and regain the blissful seat",
		"That flow'd fast by the Oracle",
		"Dove-like satst brooding on the vast Abyss",
		"What in me is dark illuminate",
		"And justify the ways of God to man",
		"Heaven hides naught from thy view",
		"O Prince, O Chief of many throned Powers",
		"Whether upheld by strength, chance, or Fate",
		"Too well I see and rue the dire event",
		"Out of evil seek to bring forth good",
		"Our labour must pervert that end",
		"And out of good find means of evil",
		"Disturb his inmost counsels from their destined aim",
		"A mind not changed by place or time",
		"The mind can make a Heaven of Hell",
		"Here at least we shall be free",
		"Their wandering gods in bestial forms",
		"O'er their loftiest towers ascends the noise of riot",
		"On his countenance cast like doubtful hue",
		"Bore semblance of worth, but not substance",
		"Of trumpets loud and clarions upreared",
		"Shone like a meteor streaming to the wind",
		"With gems and golden luster rich emblaz'd",
		"From the glittering staff unfurled the ensign",
		"Upsent a shout that tore hell's concave",
		"Frighting the reign of Chaos and Night"
	];
var grief = [
		"Now all these hearts that do on mine depend",
		"Feeling it break, with bleeding groans they pine",
		"And supplicant their sighs to you extend",
		"To leave the battery that you make 'gainst mine",
		"Each cheek a river running from a fount",
		"With brinish current downward flow'd apace",
		"O, how the channel to the stream gave grace!",
		"Who glazed with crystal gate the glowing roses",
		"That flame through water which their hue encloses",
		"O father, what a hell of witchcraft lies",
		"In the small orb of one particular tear",
		"But with the inundation of the eyes",
		"What rocky heart to water will not wear?",
		"What breast so cold that is not warmed here?",
		"O cleft effect! cold modesty, hot wrath",
		"Both fire from hence and chill extincture hath",
		"O, that infected moisture of his eye",
		"O, that false fire which in his cheek so glow'd",
		"O, that forced thunder from his heart did fly",
		"O, that sad breath his spongy lungs bestow'd",
		"O, all that borrow'd motion seeming owed",
		"Would yet again betray the fore-betray'd",
		"Come away, come away, death",
		"And in sad cypres let me be laid",
		"Fly away, fly away, breath",
		"My shroud of white, stuck all with yew",
		"My part of death, no one so true did share it",
		"Not a flower, not a flower sweet",
		"On my black coffin let there be strown",
		"My poor corse, where my bones shall be thrown",
		"A thousand thousand sighs to save",
		"Urns and odours bring away!",
		"Vapours, sighs, darken the day!",
		"Our dole more deadly looks than dying",
		"Sacred vials fill'd with tears",
		"Come, all sad and solemn shows",
		"That are quick-eyed Pleasure's foes",
		"We convent naught else but woes",
		"Fear no more the heat o' the sun",
		"Nor the furious winter's rages",
		"Thou thy worldly task hast done",
		"Home art gone, and ta'en thy wages",
		"As chimney sweepers come to dust",
		"Thou art past the tyrant's stroke",
		"Care no more to clothe and eat",
		"To thee the reed is as the oak",
		"Consign to thee, and come to dust",
		"Farewell! God knows when we shall meet again",
		"I have a faint cold fear thrills through my veins",
		"That almost freezes up the heat of life",
		"My dismal scene I needs must act alone",
		"How if, when I am laid into the tomb",
		"Shall I not then be stifled in the vault",
		"To whose foul mouth no healthsome air breathes in",
		"Or, if I live, is it not very like",
		"The horrible conceit of death and night",
		"Together with the terror of the place",
		"As in a vault, an ancient receptacle",
		"Where, for this many hundred years, the bones",
		"Of all my buried ancestors are pack'd",
		"At some hours in the night spirits resort",
		"And shrieks like mandrakes torn out of the earth",
		"That living mortals, hearing them, run mad",
		"O, if I wake, shall I not be distraught",
		"Environed with all these hideous fears",
		"And madly play with my forefathers' joints",
		"And, in this rage, with some great kinsman's bone",
		"As with a club, dash out my desperate brains",
		"What potions have I drunk of Siren tears",
		"Distilled from limbecks foul as hell within",
		"Applying fears to hopes, and hopes to fears",
		"Still losing when I saw my self to win",
		"What wretched errors hath my heart committed",
		"Whilst it hath thought it self so blessèd never",
		"In the distraction of this madding fever",
		"Beshrew that heart that makes my heart to groan",
		"For that deep wound it gives my friend and me",
		"Is't not enough to torture me alone",
		"But slave to slavery my sweet'st friend must be",
		"Me from my self thy cruel eye hath taken",
		"A torment thrice threefold thus to be crossed",
		"Prison my heart in thy steel bosom's ward",
		"O, call not me to justify the wrong",
		"That thy unkindness lays upon my heart",
		"Wound me not with thine eye but with thy tongue",
		"Yet do not so; but since I am near slain",
		"Kill me outright with looks and rid my pain",
		"Who lets so fair a house fall to decay",
		"And barren rage of death's eternal cold",
		"Be wise as thou art cruel",
		"Lest sorrow lend me words and words express",
		"The manner of my pity-wanting pain",
		"For if I should despair, I should grow mad",
		"And in my madness might speak ill of thee",
		"Now this ill-wresting world is grown so bad",
		"Mad slanderers by mad ears believèd be",
		"The beast that bears me, tired with my woe",
		"Plods dully on, to bear that weight in me",
		"The bloody spur cannot provoke him on",
		"That sometimes anger thrusts into his hide",
		"Which heavily he answers with a groan",
		"More sharp to me than spurring to his side",
		"My grief lies onward and my joy behind",
		"Tired with all these, for restful death I cry",
		"As to behold desert a beggar born",
		"And needy nothing trimmed in jollity",
		"And purest faith unhappily forsworn",
		"And gilded honour shamefully misplaced",
		"And maiden virtue rudely strumpeted",
		"And right perfection wrongfully disgraced",
		"And strength by limping sway disablèd",
		"And art made tongue-tied by authority",
		"And folly doctor-like controlling skill",
		"And simple truth miscalled simplicity",
		"And captive good attending captain ill",
		"Tired with all these, from these would I be gone",
		"No longer mourn for me when I am dead",
		"Then you shall hear the surly sullen bell",
		"Give warning to the world that I am fled",
		"From this vile world, with vilest worms to dwell",
		"Serv'd to discover sights of woe",
		"Regions of sorrow, doleful shades",
		"Where peace and rest can never dwell",
		"Hope never comes that comes to all",
		"Vaunting aloud, but rack'd with despair",
		"Here swallow'd up in endless misery",
		"Or do his errands in the gloomy deep",
		"Is this the seat that we exchange",
		"Our mournful gloom for celestial light",
		"Farewell happy fields where joy e'er dwells",
		"Hail horrors, hail infernal world",
		"Thou profoundest Hell, receive thy possessor",
		"The flower of heaven, once yours, now lost",
		"After the toil of battle to repose",
		"Your wearied virtue, the ease you find",
		"To slumber here, as in the vales of heaven",
		"Transfix us to the bottom of this gulf",
		"With monstrous shapes and sorceries abused"
	];

var types = {0:war,1:love,2:springsummer,3:fallwinter,4:fate,5:grief};

function makePoem() {
  let available=types[(Math.random()*6) | 0];
  var poemLength = (1 + (Math.random()*3)|0)*4;
  let poem = "";
  let taken = [];
  let lineNo = -1;
  for(let i = 0; i < poemLength; i++){
    if((i%4) == 0){ poem += "\n"; }
    lineNo = ((Math.random()*available.length)|0);
    while (taken.includes(lineNo)){ // if taken, increment until not taken
      lineNo++;
      if(lineNo >= available.length) lineNo=0;
    }
    taken.push(lineNo);
    poem+=available[lineNo] + "\n";
  }
  return poem;
}

function refresh(){ document.getElementById("mindspace").innerHTML = "";}
function think(){ 
  refresh();
  let poem = makePoem();
  printDelayed_pre_nosound(poem,"mindspace",10);
}
